[package]
name = "Pyco8"
version = "0.1.0"
authors = ["Michael Barz <mbarz6@gmail.com>"]

[dependencies]
cpython = "0.1"
piston = "0.37.0"
pistoncore-glutin_window = "0.46.0"
piston2d-graphics = "0.26.0"
piston2d-opengl_graphics = "0.53.0"
piston_window = "0.79.0"
